include::header.adoc[]

:title: Assignment 0: Hello CS313!
:Author Initials: ASN
:Date:    2020-02-07
:Revision: 0.1

= {title}

**Due Thursday, January 19, before midnight**

The goals for this assignment are:

* Sign-up for github
* Join slack
* Look at the website!
* (Optional) Setup your graphics development environment

:sectnums:

= Sign-up for github

Please go to github.com and register. We will use github for assignments and 
projects this semester. Email the instructor (anormoyle at brynmawr.edu) with 
your github username. 

We have made the decision to open-source our assignments and projects for this 
class. The benefit of this decision is that you will have a portfolio of work that 
you can share with employers by the end of the semester.  

One question people often have about open source is whether it will encourage 
cheating. At Bryn Mawr and Haverford, we have an honor code and incidences of 
cheating will be brought before the honor board. 
Note also that copied work will be in plain sight of everyone, including recruiters 
and employers. You need to be able to talk about your work intelligently and the 
easiest way to do that is to do your own work.

You will discover that there are many open-source resources for 
graphics online. Some of it is boiler plate and intended to be re-used. 
In general, if you use someone else's functions, classes, math implementations, or 
algorithms, you must attribute them! 

= Join slack

I will be inviting you all to join the course slack channel. In the
`#computer-graphics` channel, say and introduce yourself:

* What is your preferred name and pronouns?
* Post an image created with computer graphics with a brief sentence about it.

= Read the class web pages 

Start by reading through **all** of the link:./index.html[class webpage]!
Bookmark this page on your browser, or use some other method that helps you 
keep this information handy. All course materials and announcements will be 
posted on the course webpage! 

Pay special attention to the link:./index.html#_schedule[Schedule]. 

= (Optional) Setup your development environment on your own laptop

The computer labs will be setup for graphics (both on Windows and Linux). 
However, if you would like to work on your own laptop, following the instructions 
here:

* link:{repo}/getting-started[getting-started] 

The above repository includes detailed instructions for setting up either windows, 
linux, or mac. 

= (Optional) Setup graphics tools on your own laptop

In class, I will be using Blender, Inkscape, and Gimp:

* link:https://blender.org[Blender]: A 3D modeling tool with photorealistic rendering features. Blender can be used to view and create 3D models. We will use this in class demos and you may find it useful (and fun) to 
use yourself. 
* link:https://gimp.org[Gimp]: An open source image program, similar to Photoshop. Gimp can be used to view and edit images, including textures.
* link:https://inkscape.org[Inkscape]: An open source vector image program. 

Here is a great tutorial for learning Blender:

* link:https://www.youtube.com/watch?v=TPrnSACiTJ4[Blender Beginner Tutorial]
