include::header.adoc[]

:title: Study Guide 4: Advanced rendering techniques
:Author Initials: ASN
:Date:    2020-08-15
:Revision: 0.1
:stem: latexmath

= {title}

Final Exam Study Topics:

Everything from link:studyguide3.html[Study Guide 3] plus

* Advanced rendering techniques
* Intersection testing
* Ray-based selection

Please also use your lab worksheets as study resources.

[discrete]
= Short Answers

* What is a billboard?
* What is a cubemap?
* How can we implement reflective materials using shaders?
* How can we implement refractive materials using shaders?
* What is the fresnel effect?
* How can we implement a toon material using shaders?
* How does additive blending differ from alpha blending?
* What is multi-pass rendering?
* Give an example of an algorithm that uses multi-pass rendering?
* What is render-to-texture?
* What is a shadow map?
* Why do jaggy artifacts happen in shadow mapping? How can we avoid these artifacts? 
* What is a height map?
* What is a bump, or normal map?
* What are some advantages of bump mapping?
* Suppose we would like to screen an effect that blurs the screen after rendering? How would we implement this effect using shaders?
* Suppose we would like to screen an effect that inverts the colors of the screen after rendering? How would we implement this effect using shaders?
* What is a depth texture?
* How can we access a shadow map in our fragment map to test whether a point is in shadow?
* Derive an expression for testing the intersection point for a ray and the plane Z = 2 (normal is (0,0,1)). Recall that a ray that hits a plane satisfies stem:[(p + tv - a) \ldot n = 0].
* What steps do we need to take to convert a screen position to a world position?

[discret]
= Sample Questions

* Suppose the user clicks on the screen at position (300, 200). The screen has dimensions (400, 400). What homogeneous clip coordinates, or projected coordinates, correspond to this position?
* Suppose the eye position is at (0,0,2) and the user clicks at world position (-1.2, -0.5). What ray would we use for intersection testing?
* Test whether the previous ray intersects a sphere at position (-1, 0, 0) and radius 2.0 using the sphere intersection function covered in class. [Assume you will have the algorithm on an exam]
* Test whether the previous ray intersects a cube at position (-1, 0, 0) with size 2.0 using the cube intersection function covered in class. [Assume you will have the algorithm on an exam]
* Suppose we have a vector (-1,1,0) that reflects around a normal (0,0.5, sqrt(3)/2). Compute the component of the vector that is perpendicular to the normal. Compute the component of the vector that is parellel to the normal. What is the reflection vector?
* Suppose we wish to orient a point billboard so it always faces the eye. If the eye is at position (0,0,2) and the billboard is located at (1,1,2). What rotation matrix should we use to point towards the eye? Assume that billboard as (0,0,1) as forward and (0,1,0) as up in local coordinates.
* Suppose we wish to orient an axis billboard so it always faces the eye. If the eye is at position (0,0,2) and the billboard is located at (1,1,2). What rotation matrix should we use to point towards the eye? Assume that billboard as (0,0,1) as forward and (0,1,0) as up in local coordinates.
* Sketch an algorithm for a particle system that could be used to display smoke. 

////

== Ray tracing/marching

* What is the difference between ray tracing and rasterization for how it renders objects?
* In a ray tracer, how do we determine the color of each pixel?
* In a ray tracer, how do we determine that a pixel is in shadow?
* What is a signed-distance-function?
* What is the difference between ray marching an ray tracing?

= Sample Questions

* Suppose we are ray tracing a 400x300 image. The camera is at location (0,0,2) and the image plane is centered at (0,0,0) with minimum corner at (-2,-1.5) and maximum corner at (2, 1.5). What is the camera ray at pixel (100, 100)?
* Suppose we have a ray at position (0,0,2) and direction (0,0,-1). At what point would it intersect the sphere centered at (1,0,0) with radius (10)?
* Suppose we have a ray at position (0,0,2) and direction (0,0,-1). At what point would it intersect the box centered at (0,0,0) with dimensions (3,1,1)?
* Suppose we have a ray at position (0,0,2) and direction (0,0,-1). At what point would it intersect the triangle with corners (-1,-1,0), (1,-1,0), (0,4,0)?

NOTE: You will be given psuedocode on your exam for intersection testing.
////